### ISSUE TITLE
Community location glitches after submitting

### ISSUE THREAD

**Issue by jasonsvoboda** [BrightonBTC/inmytown.social#1]
When creating or editing my community and setting the appropriate location "Las Vegas, NV", after hitting submit, you can see the location glitch (lat/lon) and then it gets displayed as "Las, Vegas" and the map jumps to some random place in Tennessee. 

Ex: https://www.inmytown.social/community/c5f10db3dab9768af16156ae4311bcdd2c2eeea7356befd4a91fa1ac3cdc4dbb

**Comment by jasonsvoboda** [comment]
![meet1](https://github.com/BrightonBTC/inmytown.social/assets/19472831/070396c5-3b9a-4567-a67b-1030b194f7b1)
![meet2](https://github.com/BrightonBTC/inmytown.social/assets/19472831/c439ce2e-0335-42f7-ba17-8ef58e263463)

**Comment by BrightonBTC** [comment]
Thanks for trying the app and reporting this, @jasonsvoboda .
The issue should be fixed now but you may need to edit your existing community and events to get location strings and maps to display correctly.

**Comment by jasonsvoboda** [comment]
I just did and while the city now does display correctly, the map does not. When I first select Las Vegas and hit the green check, it does zoom to the correct map but when I save the community, the map reverts to the same incorrect one. I also noticed the latitude and longitude are backwards from what Vegas actually is. When I select Vegas, this is what is returned under the map.

Lat: -115.13721999999999
Lon: 36.17497
Zoom: 9

https://www.latlong.net/place/las-vegas-strip-nv-usa-26560.html

Okay, so I just did it one more time and when I click submit, the I noticed the latitude jumps to -80 something - screen refreshed back to community page before I could read it, but I did see that change so I definitely think this has something to do with that or may be a separate issue?

**Comment by BrightonBTC** [comment]
I think this should be working now. However, to change the map you will first need to change the location (no need to save it) and then change it back to Las Vegas. Then save the community again.

The map and location stuff definitely still needs a lot of work but it should at least show the correct coordinates and map now. Cheers.
